### PR TITLE
Update youtube-channels.csv

### PR DESCRIPTION
**Pull request by SourcingDenis**
adding diskevich youtube channel

### CODE REVIEW

**Comment by stephanebruckert** [comment]
Already exists here https://open.spotify.com/playlist/0CrF4KRcPtP4AAYORttPT9
However, I listened to it recently, and there are a bunch of incorrect tracks - need to fix it

**Comment by SourcingDenis** [comment]
hey hey 
thank you
but why i can't see it either through web application neither from Spotify playlists? :(
thx in advance for your help @stephanebruckert

**Comment by SourcingDenis** [comment]
ah sorry I see the spotify playlist however doesn't find myself on the website

**Comment by stephanebruckert** [comment]
The spotify profile only shows max 50 playlists I think
And you are right it doesn't appear https://mirror.fm/channels/, but should! There is also a limit of 500 there, which I need to increase

**Comment by stephanebruckert** [comment]
Just realised you are diskevich :sweat_smile: good to see you here!

**Pull request closed without merging**
